spring:
  application.name: temperature



# All traces should be sent to latency analysis tool
management.tracing.sampling.probability: 1.0

management.endpoint.prometheus.enabled: true
management.endpoints.web.exposure.include: "*"
management.endpoint.health.show-details: ALWAYS

management:
  otlp:
    metrics:
      export:
        url: http://localhost:4318/v1/metrics
    tracing:
      endpoint: http://opentelemetry-collector:4318/v1/traces
      export:
  tracing:
    sampling:
      probability: 1.0